ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/

# ifdef VENDOR_EDIT 
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  device_info.o
# endif /* VENDOR_EDIT */